services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:9.2.0
    environment:
      - NETWORK=preprod
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "[ \"$(cardano-cli query tip --testnet-magic=1 --socket-path=/ipc/node.socket | tail -c 9 | head -c 5)\" == \"100.0\" ]"]
      interval: 10s
      retries: 8640
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  delegate-node-a:
    build:
      context: "../.."
      dockerfile: "docker/node/Dockerfile"
    depends_on:
      cardano-node:
        condition: service_healthy
    command: "config.json"
    volumes:
      - type: "bind"
        source: "./config-a.json"
        target: "/app/config.json"
      - type: "bind"
        source: "keys"
        target: "/app/keys"
      - type: "volume"
        source: "node-ipc"
        target: "/app/node-ipc"
      - type: "volume"
        source: "hydra-persist-a"
        target: "/app/hydra-persist"

  delegate-node-b:
    build:
      context: "../.."
      dockerfile: "docker/node/Dockerfile"
    depends_on:
      cardano-node:
        condition: service_healthy
    command: "config.json"
    volumes:
      - type: "bind"
        source: "./config-b.json"
        target: "/app/config.json"
      - type: "bind"
        source: "keys"
        target: "/app/keys"
      - type: "volume"
        source: "node-ipc"
        target: "/app/node-ipc"
      - type: "volume"
        source: "hydra-persist-b"
        target: "/app/hydra-persist"

volumes:
  hydra-persist-a:
  hydra-persist-b:
  node-db:
  node-ipc:
